### 

In [33]:
import numpy as np

a = np.array([
    [0, 1, 2, 1, 0],
    [3, 4, 5, 4, 3],
    [6, 7, 8, 7, 6],
    [3, 4, 5, 4, 4],
    [0, 1, 2, 1, 0]
])
b = np.array([1, 2, 3, 4, 5])

c = np.empty((5, 5))


# 結果を格納する配列を先に作る
### timeitで計測

In [35]:
%%timeit
for i in range(a.shape[0]):
    c[i, :] = a[i, :] + b

The slowest run took 25.44 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.86 µs per loop


### 

In [36]:
c

array([[  1.,   3.,   5.,   5.,   5.],
       [  4.,   6.,   8.,   8.,   8.],
       [  7.,   9.,  11.,  11.,  11.],
       [  4.,   6.,   8.,   8.,   9.],
       [  1.,   3.,   5.,   5.,   5.]])

### 8.9. NumPy を用いた重回帰分析

In [37]:
# Xの定義
X = np.array([
    [2, 3],
    [2, 5],
    [3, 4],
    [5, 9],
])

X

array([[2, 3],
       [2, 5],
       [3, 4],
       [5, 9]])

In [38]:
# データ数（X.shape[0]) と同じ数だけ 1 が並んだ配列
ones = np.ones((X.shape[0], 1))

# concatenate を使い、1 次元目に 1 を付け加える
X = np.concatenate((ones, X), axis=1)

# 先頭に 1 が付け加わったデザイン行列
X


array([[ 1.,  2.,  3.],
       [ 1.,  2.,  5.],
       [ 1.,  3.,  4.],
       [ 1.,  5.,  9.]])

### また、目標値が以下で与えられたとします。

In [39]:
# t の定義
t = np.array([1, 5, 6, 8])

t

array([1, 5, 6, 8])

### 重回帰分析は、正規方程式を解くことで最適な 1 次方程式の重みを決定することができました。 正規方程式の解は以下のようなものでした。
### todo 数式の書き方を調べる

これを、4 つのステップに分けて計算していきます。

まずは、XTX の計算です。ndarrayに対して .T で転置した配列を得られます。



In [40]:
# Step 1
xx = np.dot(X.T, X)

xx


array([[   4.,   12.,   21.],
       [  12.,   42.,   73.],
       [  21.,   73.,  131.]])

### 次に、この逆行列を計算します。

In [41]:
# Step 2
xx_inv = np.linalg.inv(xx)

xx_inv


array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

逆行列の計算は np.linalg.inv() で行うことができます。

次に、XTt の計算をします。



In [ ]:
# Step 3
xt = np.dot(X.T, t)

xt